#!/bin/bash

mode="$1"

if [[ "$mode" == "O" ]] ; then
	# optimised
	ADDFLAGS="-O3 -g0 -march=native -pipe -fomit-frame-pointer"
elif [[ "$mode" == "S" ]] ; then
    ADDFLAGS="-fsanitize=address -g -O0 -Wall -Wfatal-errors -Werror -Wno-error=unused-variable -Wno-error=unused-but-set-variable -Wno-error=deprecated-declarations -Wformat-truncation=1 -fdiagnostics-color=auto"
    LDFLAGS="-fsanitize=address $LDFLAGS"
    xtra_flags="--disable-shared"
elif [[ "$mode" == "D" ]] ; then
    ADDFLAGS="-O0 -g3 -Wall -Wfatal-errors -Werror -Wno-error=unused-variable -Wno-error=unused-but-set-variable -Wno-error=deprecated-declarations -Wformat-truncation=1 -fdiagnostics-color=auto"
else
	ADDFLAGS="-O2 -g  -fdiagnostics-color=auto -mtune=generic -pipe"
fi

export CFLAGS="$ADDFLAGS $CFLAGS"
export CXXFLAGS="$ADDFLAGS $CXXFLAGS"


echo "CFLAGS   = '$CFLAGS'"
echo "CXXFLAGS = '$CXXFLAGS'"
echo "LDFLAGS  = '$LDFLAGS'"
echo "PREFIX = '$PREFIX'"

export PREFIX
export CFLAGS
export CXXFLAGS
export LDFLAGS

./configure $xtra_flags --prefix=$PREFIX --enable-default-qrfit $2 $3 $4 $5 $6
