# Things you might need or want to modify:
#
# CXX, AR, ARFLAGS, RANLIB, DSO, CXXFLAGS, FFLAGS, LDFLAGS, ARCH
#
# do so here if you wish....
CFLAGS = -g
CXXFLAGS = -g
#Common for solaris:
# For apus:
#CXXFLAGS = -I/opt/SUNWspro/WS6U2/include/cc 
# For atlas:
#CXXFLAGS = -I/opt/SUNWspro/WS6/include/cc/
#CFLAGS =  -I/opt/SUNWspro/WS6/include/cc/
#LDFLAGS += -lsunmath


ARFLAGS = crv
CC = gcc
CXX = g++



# Tell us where PGPLOT is (unless you don't want plugins that use PGPLOT)
# NOTE, if you get errors regarding -lpng, try taking it out: probably
# your PGPLOT wasn't configured to use the PNG device
# On SUN machines you may need -LM77 -lF77 added
ICPGPLOT = -I$(PGPLOT_DIR)
#LCPGPLOT = -L$(PGPLOT_DIR) -lcpgplot -lpgplot  -L/usr/X11R6/lib -lX11  $(LF) -pg -lM77 -lF77 -lf2c
# The next version of the LCPGPLOT line appears to work on linux at UBC. 
# IHS Jan 14 2009
LCPGPLOT = -L$(PGPLOT_DIR) -lcpgplot -lpgplot  -L/usr/X11R6/lib -lX11 -lpng -lg2c -pg

# Choose your fortran compiler:
# FC = g77 | gfortran | something else (defaults to f77)
FC = g77

# Flags required to make your fortran compiler spit out symbol names that
#  are lowercase, with a single appended underscore.
# (note, this can be done automatically if you set FC = g77 or gfortran)
# FUNDERSCORE = ...

# Linking with fortran
# (note, this can be done automatically if you set FC = g77 or gfortran)
#LF = -L/sw/lib -lg2c

# Long-double emulation
# This is not needed for linux or sun/solaris, nor OS X 10.4 or later.
# Others may wish to use LONGDOUBLE = qd, which requires the "quad precision"
# C++ library libqd: http://crd.lbl.gov/~dhbailey/mpdist/qd.tar.gz
# This means you also need to set up CXXFLAGS and LDFLAGS.
# NOTE, support for this in tempo2 is currently broken!!
#LONGDOUBLE = qd
#CXXFLAGS = -O -I$(PSRHOME)/packages/$(LOGIN_ARCH)/include
#LDFLAGS += -L$(PSRHOME)/packages/$(LOGIN_ARCH)/lib -lqd

