#!/bin/bash

cd `dirname $0`

echo "Running update ..."
git pull origin

while [[ $# > 0 ]] ; do
    key="$1"

    case $key in
        --temponest)
            if [[ ! -e TempoNest ]] ; then
                git clone https://github.com/LindleyLentati/TempoNest.git
            fi
            shift
            ;;
        *)
            # unknown option
            shift
            ;;
    esac
done

if [[ -e TempoNest ]] ; then
    echo "update temponest"
    cd TempoNest
    git pull origin
fi
