#!/bin/bash

echo "Updating repository URL"
git remote show origin | grep -q https
ex=$?
if [[ $ex -eq 0 ]] ; then
    echo "   == Anonymous checkout"
    git remote set-url origin https://bitbucket.org/psrsoft/tempo2.git
else
    echo "   == Developer checkout"
    git remote set-url origin git@bitbucket.org:psrsoft/tempo2.git
fi


echo "Running update ..."
git pull origin
git checkout ./update
